spring:
  application:
    name: sdy-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/woshiyonghuhuanshenme/sdy-configs.git
          search-paths: xproject-config
          username: *
          password: *